CREATE OR REPLACE FUNCTION public.upsert_vehicles_from_stage()
    RETURNS BIGINT
    LANGUAGE plpgsql
    AS
    $$
    DECLARE num_records BIGINT;
    BEGIN
        WITH upserted AS (
            INSERT INTO public.vehicles(
                id, type, link_self,
                marka, kategoria_pojazdu, typ_attr, model, wariant, wersja,
                rodzaj_pojazdu, podrodzaj_pojazdu, przeznaczenie_pojazdu, pochodzenie_pojazdu,
                rodzaj_tabliczki_znamionowej, sposob_produkcji, rok_produkcji,
                data_pierwszej_rejestracji_w_kraju, data_ostatniej_rejestracji_w_kraju, data_rejestracji_za_granica,
                pojemnosc_skokowa_silnika, stosunek_mocy_do_masy_motocykle, moc_netto_silnika, moc_netto_silnika_hybrydowego,
                masa_wlasna, masa_gotowa_do_jazdy, dmc, max_dmc, dopuszczalna_ladownosc, max_ladownosc, dmc_zespolu,
                liczba_osi, dopuszczalny_nacisk_osi, maksymalny_nacisk_osi,
                max_masa_przyczepy_z_hamulcem, max_masa_przyczepy_bez_hamulca,
                liczba_miejsc_ogolem, liczba_miejsc_siedzacych, liczba_miejsc_stojacych,
                rodzaj_paliwa, paliwo_alt_1, paliwo_alt_2,
                srednie_zuzycie_paliwa, poziom_emisji_co2,
                rodzaj_zawieszenia, urzadzenie_radarowe,
                hak, kierownica_po_prawej, kierownica_po_prawej_pierwotnie, katalizator_pochlaniacz,
                nazwa_producenta, kod_its,
                rozstaw_kol_osi_kierowanej_pozostalych, max_rozstaw_kol, avg_rozstaw_kol, min_rozstaw_kol,
                redukcja_emisji_spalin,
                data_pierwszej_rejestracji,
                rodzaj_kodowania, kod_rodzaj_podrodzaj_przeznaczenie,
                data_wyrejestrowania_pojazdu, przyczyna_wyrejestrowania_pojazdu, data_wprowadzenia_danych,
                rejestracja_wojewodztwo, rejestracja_gmina, rejestracja_powiat,
                wlasciciel_wojewodztwo, wlasciciel_powiat, wlasciciel_gmina, wlasciciel_wojewodztwo_kod,
                wojewodztwo_kod, poziom_emisji_co2_paliwo_alt_1
            )
            SELECT 
                id, type, link_self,
                marka, kategoria_pojazdu, typ_attr, model, wariant, wersja,
                rodzaj_pojazdu, podrodzaj_pojazdu, przeznaczenie_pojazdu, pochodzenie_pojazdu,
                rodzaj_tabliczki_znamionowej, sposob_produkcji, rok_produkcji,
                data_pierwszej_rejestracji_w_kraju, data_ostatniej_rejestracji_w_kraju, data_rejestracji_za_granica,
                pojemnosc_skokowa_silnika, stosunek_mocy_do_masy_motocykle, moc_netto_silnika, moc_netto_silnika_hybrydowego,
                masa_wlasna, masa_gotowa_do_jazdy, dmc, max_dmc, dopuszczalna_ladownosc, max_ladownosc, dmc_zespolu,
                liczba_osi, dopuszczalny_nacisk_osi, maksymalny_nacisk_osi,
                max_masa_przyczepy_z_hamulcem, max_masa_przyczepy_bez_hamulca,
                liczba_miejsc_ogolem, liczba_miejsc_siedzacych, liczba_miejsc_stojacych,
                rodzaj_paliwa, paliwo_alt_1, paliwo_alt_2,
                srednie_zuzycie_paliwa, poziom_emisji_co2,
                rodzaj_zawieszenia, urzadzenie_radarowe,
                hak, kierownica_po_prawej, kierownica_po_prawej_pierwotnie, katalizator_pochlaniacz,
                nazwa_producenta, kod_its,
                rozstaw_kol_osi_kierowanej_pozostalych, max_rozstaw_kol, avg_rozstaw_kol, min_rozstaw_kol,
                redukcja_emisji_spalin,
                data_pierwszej_rejestracji,
                rodzaj_kodowania, kod_rodzaj_podrodzaj_przeznaczenie,
                data_wyrejestrowania_pojazdu, przyczyna_wyrejestrowania_pojazdu, data_wprowadzenia_danych,
                rejestracja_wojewodztwo, rejestracja_gmina, rejestracja_powiat,
                wlasciciel_wojewodztwo, wlasciciel_powiat, wlasciciel_gmina, wlasciciel_wojewodztwo_kod,
                wojewodztwo_kod, poziom_emisji_co2_paliwo_alt_1
            FROM public.staging_vehicles
            ON CONFLICT (id) DO UPDATE SET
                type = EXCLUDED.type,
                link_self = EXCLUDED.link_self,
                marka = EXCLUDED.marka,
                kategoria_pojazdu = EXCLUDED.kategoria_pojazdu,
                typ_attr = EXCLUDED.typ_attr,
                model = EXCLUDED.model,
                wariant = EXCLUDED.wariant,
                wersja = EXCLUDED.wersja,
                rodzaj_pojazdu = EXCLUDED.rodzaj_pojazdu,
                podrodzaj_pojazdu = EXCLUDED.podrodzaj_pojazdu,
                przeznaczenie_pojazdu = EXCLUDED.przeznaczenie_pojazdu,
                pochodzenie_pojazdu = EXCLUDED.pochodzenie_pojazdu,
                rodzaj_tabliczki_znamionowej = EXCLUDED.rodzaj_tabliczki_znamionowej,
                sposob_produkcji = EXCLUDED.sposob_produkcji,
                rok_produkcji = EXCLUDED.rok_produkcji,
                data_pierwszej_rejestracji_w_kraju = EXCLUDED.data_pierwszej_rejestracji_w_kraju,
                data_ostatniej_rejestracji_w_kraju = EXCLUDED.data_ostatniej_rejestracji_w_kraju,
                data_rejestracji_za_granica = EXCLUDED.data_rejestracji_za_granica,
                pojemnosc_skokowa_silnika = EXCLUDED.pojemnosc_skokowa_silnika,
                stosunek_mocy_do_masy_motocykle = EXCLUDED.stosunek_mocy_do_masy_motocykle,
                moc_netto_silnika = EXCLUDED.moc_netto_silnika,
                moc_netto_silnika_hybrydowego = EXCLUDED.moc_netto_silnika_hybrydowego,
                masa_wlasna = EXCLUDED.masa_wlasna,
                masa_gotowa_do_jazdy = EXCLUDED.masa_gotowa_do_jazdy,
                dmc = EXCLUDED.dmc,
                max_dmc = EXCLUDED.max_dmc,
                dopuszczalna_ladownosc = EXCLUDED.dopuszczalna_ladownosc,
                max_ladownosc = EXCLUDED.max_ladownosc,
                dmc_zespolu = EXCLUDED.dmc_zespolu,
                liczba_osi = EXCLUDED.liczba_osi,
                dopuszczalny_nacisk_osi = EXCLUDED.dopuszczalny_nacisk_osi,
                maksymalny_nacisk_osi = EXCLUDED.maksymalny_nacisk_osi,
                max_masa_przyczepy_z_hamulcem = EXCLUDED.max_masa_przyczepy_z_hamulcem,
                max_masa_przyczepy_bez_hamulca = EXCLUDED.max_masa_przyczepy_bez_hamulca,
                liczba_miejsc_ogolem = EXCLUDED.liczba_miejsc_ogolem,
                liczba_miejsc_siedzacych = EXCLUDED.liczba_miejsc_siedzacych,
                liczba_miejsc_stojacych = EXCLUDED.liczba_miejsc_stojacych,
                rodzaj_paliwa = EXCLUDED.rodzaj_paliwa,
                paliwo_alt_1 = EXCLUDED.paliwo_alt_1,
                paliwo_alt_2 = EXCLUDED.paliwo_alt_2,
                srednie_zuzycie_paliwa = EXCLUDED.srednie_zuzycie_paliwa,
                poziom_emisji_co2 = EXCLUDED.poziom_emisji_co2,
                rodzaj_zawieszenia = EXCLUDED.rodzaj_zawieszenia,
                urzadzenie_radarowe = EXCLUDED.urzadzenie_radarowe,
                hak = EXCLUDED.hak,
                kierownica_po_prawej = EXCLUDED.kierownica_po_prawej,
                kierownica_po_prawej_pierwotnie = EXCLUDED.kierownica_po_prawej_pierwotnie,
                katalizator_pochlaniacz = EXCLUDED.katalizator_pochlaniacz,
                nazwa_producenta = EXCLUDED.nazwa_producenta,
                kod_its = EXCLUDED.kod_its,
                rozstaw_kol_osi_kierowanej_pozostalych = EXCLUDED.rozstaw_kol_osi_kierowanej_pozostalych,
                max_rozstaw_kol = EXCLUDED.max_rozstaw_kol,
                avg_rozstaw_kol = EXCLUDED.avg_rozstaw_kol,
                min_rozstaw_kol = EXCLUDED.min_rozstaw_kol,
                redukcja_emisji_spalin = EXCLUDED.redukcja_emisji_spalin,
                data_pierwszej_rejestracji = EXCLUDED.data_pierwszej_rejestracji,
                rodzaj_kodowania = EXCLUDED.rodzaj_kodowania,
                kod_rodzaj_podrodzaj_przeznaczenie = EXCLUDED.kod_rodzaj_podrodzaj_przeznaczenie,
                data_wyrejestrowania_pojazdu = EXCLUDED.data_wyrejestrowania_pojazdu,
                przyczyna_wyrejestrowania_pojazdu = EXCLUDED.przyczyna_wyrejestrowania_pojazdu,
                data_wprowadzenia_danych = EXCLUDED.data_wprowadzenia_danych,
                rejestracja_wojewodztwo = EXCLUDED.rejestracja_wojewodztwo,
                rejestracja_gmina = EXCLUDED.rejestracja_gmina,
                rejestracja_powiat = EXCLUDED.rejestracja_powiat,
                wlasciciel_wojewodztwo = EXCLUDED.wlasciciel_wojewodztwo,
                wlasciciel_powiat = EXCLUDED.wlasciciel_powiat,
                wlasciciel_gmina = EXCLUDED.wlasciciel_gmina,
                wlasciciel_wojewodztwo_kod = EXCLUDED.wlasciciel_wojewodztwo_kod,
                wojewodztwo_kod = EXCLUDED.wojewodztwo_kod,
                poziom_emisji_co2_paliwo_alt_1 = EXCLUDED.poziom_emisji_co2_paliwo_alt_1
            RETURNING 1
        )
        SELECT COUNT(*) INTO num_records FROM upserted;
        
        TRUNCATE TABLE public.staging_vehicles;
        RETURN num_records;
    END;
    $$