CREATE TABLE IF NOT EXISTS public.vehicles (
  id                               text PRIMARY KEY,
  type                             text,
  link_self                        text,
  marka                            text,
  kategoria_pojazdu                text,
  typ_attr                         text,
  model                            text,
  wariant                          text,
  wersja                           text,
  rodzaj_pojazdu                   text,
  podrodzaj_pojazdu                text,
  przeznaczenie_pojazdu            text,
  pochodzenie_pojazdu              text,
  rodzaj_tabliczki_znamionowej     text,
  sposob_produkcji                 text,
  rok_produkcji                    text,
  data_pierwszej_rejestracji_w_kraju date,
  data_ostatniej_rejestracji_w_kraju date,
  data_rejestracji_za_granica      date,
  pojemnosc_skokowa_silnika        double precision,
  stosunek_mocy_do_masy_motocykle  double precision,
  moc_netto_silnika                double precision,
  moc_netto_silnika_hybrydowego    double precision,
  masa_wlasna                      integer,
  masa_gotowa_do_jazdy             integer,
  dmc                              integer,
  max_dmc                          integer,
  dopuszczalna_ladownosc           integer,
  max_ladownosc                    integer,
  dmc_zespolu                      integer,
  liczba_osi                       integer,
  dopuszczalny_nacisk_osi          double precision,
  maksymalny_nacisk_osi            double precision,
  max_masa_przyczepy_z_hamulcem    integer,
  max_masa_przyczepy_bez_hamulca   integer,
  liczba_miejsc_ogolem             integer,
  liczba_miejsc_siedzacych         integer,
  liczba_miejsc_stojacych          integer,
  rodzaj_paliwa                    text,
  paliwo_alt_1                     text,
  paliwo_alt_2                     text,
  srednie_zuzycie_paliwa           double precision,
  poziom_emisji_co2                double precision,
  rodzaj_zawieszenia               text,
  urzadzenie_radarowe              text,
  hak                              boolean,
  kierownica_po_prawej             boolean,
  kierownica_po_prawej_pierwotnie  boolean,
  katalizator_pochlaniacz          boolean,
  nazwa_producenta                 text,
  kod_its                          text,
  rozstaw_kol_osi_kierowanej_pozostalych double precision,
  max_rozstaw_kol                  integer,
  avg_rozstaw_kol                  integer,
  min_rozstaw_kol                  integer,
  redukcja_emisji_spalin           text,
  data_pierwszej_rejestracji       date,
  rodzaj_kodowania                 text,
  kod_rodzaj_podrodzaj_przeznaczenie text,
  data_wyrejestrowania_pojazdu     date,
  przyczyna_wyrejestrowania_pojazdu text,
  data_wprowadzenia_danych         date,
  rejestracja_wojewodztwo          text,
  rejestracja_gmina                text,
  rejestracja_powiat               text,
  wlasciciel_wojewodztwo           text,
  wlasciciel_powiat                text,
  wlasciciel_gmina                 text,
  wlasciciel_wojewodztwo_kod       text,
  wojewodztwo_kod                  text,
  poziom_emisji_co2_paliwo_alt_1   double precision
);

CREATE INDEX IF NOT EXISTS vehicles_wojew_idx ON public.vehicles (wojewodztwo_kod);
CREATE INDEX IF NOT EXISTS vehicles_brin_dprwk ON public.vehicles USING brin (data_pierwszej_rejestracji_w_kraju);
